// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbiwepvmnwcjurxxccej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiaXdlcHZtbndjanVyeHhjY2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTQ3MzgsImV4cCI6MjA2MDE5MDczOH0.Qu0wHZOkLCDuNmv9YDkDW7kpLqhuHl4099R4s1JAS1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);